### ISSUE TITLE
Run Basecoin on Docker

### ISSUE THREAD

**Issue by Andlinks-Yourturn** [tendermint/basecoin#1]
Hello, 
I tried to run basecoin with Docker.
After pulling the images, the initialization is successful. but ` docker run -it --rm -v  "/home/andlinks/docs/basecoin:/basecoin" tendermint/basecoin`
only shows`loading existing db
I[08-30|11:13:09.293] Done setting Account via SetOption           module=app result=Success
I[08-30|11:13:09.293] Starting Basecoin with Tendermint            module=main chain_id=test_chain_id` 
then there was no more output.
I wish there could be more instructions on how to use this image to run `basecli` commands properly.
Thx

**Comment by zramsay** [comment]
@Andlinks-Yourturn this repo is here largely for legacy purposes. Please see https://github.com/cosmos/cosmos-sdk ... there is work going on in unstable branches. We have docs forthcoming in this area; http://cosmos-sdk.readthedocs.io
